/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import Admin.Dashboard;
import static Admin.Dashboard.ab;
import static Admin.Dashboard.brg;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import koneksi.Session;
import koneksi.koneksi;

/**
 *
 * @author asus
 */
public class Barang extends javax.swing.JPanel {
    
    public void pendapatan(){
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String tanggal = currentDate.format(dateFormatter);
        try{
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT sum(grand_total) from transaksi where tanggal = '"+tanggal+"'");
            while(rs.next()){
                txttotalpemasukan.setText(rs.getString("sum(grand_total)"));
            }
        }catch(Exception e){
            
        }
    }
    
     public void tampilkanTabel1(){
        DefaultTableModel model = new DefaultTableModel();
        
        tabeldashboard.setModel(model);
        
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        model.addColumn("Keuntungan");
        
        
       try {
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * from barang");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("harga_jual"),
                    rs.getString("stok"),
                    rs.getString("keuntungan"),
                    
                });
                tabeldashboard.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }
    }
    
    public void jumlahbarang(){
        try{
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT count(id_barang) from barang");
            while(rs.next()){
                txtjumlahproduk.setText(rs.getString("count(id_barang)"));
            }
        }catch(Exception e){
            System.out.println("gagal"+e.getMessage());
        }
    }
    
    public void datauser(){
        try{
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT count(nik) from user");
            while(rs.next()){
                txtdatauser.setText(rs.getString("count(nik)"));
            }
        }catch(Exception e){
            System.out.println("gagal"+e.getMessage());
        }
    }
        
    public Barang() {
        try{
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
            {
                if ("".equals(info.getName()))
                {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(Exception ex){
            
        }

    
        initComponents();
      
        txttotalpemasukan.setText("0");
        tabeldashboard.getTableHeader().setFont(new Font("Fredoka One", Font.CENTER_BASELINE, 16));
        tabeldashboard.getTableHeader().setOpaque(false);
        tabeldashboard.getTableHeader().setBackground(new Color(241,175,9));
        tabeldashboard.getTableHeader().setForeground(new Color(0, 0, 0));
        tabeldashboard.setRowHeight(25);
        
        
        txtusernamee1.setText(Session.get_username());
        tampilkanTabel1();
        jumlahbarang();
        datauser();
        
        pendapatan();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusernamee1 = new javax.swing.JLabel();
        txtjumlahproduk = new javax.swing.JLabel();
        txtdatauser = new javax.swing.JLabel();
        txtusernamee3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeldashboard = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1571, 965));
        setPreferredSize(new java.awt.Dimension(1571, 965));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusernamee1.setFont(new java.awt.Font("YouYuan", 1, 18)); // NOI18N
        txtusernamee1.setText("jLabel2");
        add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, 150, 30));

        txtjumlahproduk.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtjumlahproduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(txtjumlahproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 200, 70));

        txtdatauser.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtdatauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(txtdatauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 200, 70));

        txtusernamee3.setFont(new java.awt.Font("YouYuan", 1, 18)); // NOI18N
        txtusernamee3.setText("Hallo, Selamat Datang");
        add(txtusernamee3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 220, 30));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 340, 70, 80));
        add(txttotalpemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 200, 220, 60));

        tabeldashboard = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabeldashboard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabeldashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldashboard.setFocusable(false);
        tabeldashboard.setSelectionBackground(new java.awt.Color(241, 175, 9));
        tabeldashboard.getTableHeader().setResizingAllowed(false);
        tabeldashboard.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabeldashboard);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 1450, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/dashboard (8)_2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 965));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

       brg.setVisible(false);
       ab.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabeldashboard;
    private javax.swing.JLabel txtdatauser;
    private javax.swing.JLabel txtjumlahproduk;
    public static final javax.swing.JLabel txttotalpemasukan = new javax.swing.JLabel();
    private javax.swing.JLabel txtusernamee1;
    private javax.swing.JLabel txtusernamee3;
    // End of variables declaration//GEN-END:variables
}
