/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import Admin.Dashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Session;
import koneksi.koneksi;
import static panel.Barang.tabeldashboard;
import static panel.dashboard.tabelbarang;


/**
 *
 * @author asus
 */
public class Brg_edt extends javax.swing.JPanel {

    /**
     * Creates new form Brg_edt
     */
    public void tampilkanTabel(){
        DefaultTableModel model = new DefaultTableModel();
        
        tabelbarang.setModel(model);
        
        model.addColumn("kode barang");
        model.addColumn("Nama barang");
        model.addColumn("Harga beli");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        model.addColumn("Keuntungan");
        
        
       try {
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * from barang");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("harga_jual"),
                    rs.getString("stok"),
                    rs.getString("keuntungan"),
                    
                });
                tabelbarang.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }
    }
    
    public void tampilkanTabel1(){
        DefaultTableModel model = new DefaultTableModel();
        
        tabeldashboard.setModel(model);
        
        model.addColumn("Kode Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        model.addColumn("Keuntungan");
        
        
       try {
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * from barang");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("harga_jual"),
                    rs.getString("stok"),
                    rs.getString("keuntungan"),
                    
                });
                tabeldashboard.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }
    }
    
    
    public void clear(){
        txt_kodebarang.setText("");
        txt_namabarang.setText("");
        txt_hargabeli.setText("");
        txt_stok.setText("");
        txt_keuntungan.setText("");
        txt_hargajual.setText("");
    }
    
    public Brg_edt() {
        initComponents();
        txtusernamee1.setText(Session.get_username());
        txt_keuntungan.requestFocus();
        clear();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton1 = new Button.MyButton();
        txt_keuntungan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_hargajual = new javax.swing.JTextField();
        txtusernamee1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1571, 965));
        setPreferredSize(new java.awt.Dimension(1571, 965));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton1.setBackground(new java.awt.Color(255, 228, 0));
        myButton1.setText("Edit");
        myButton1.setBorderColor(new java.awt.Color(255, 228, 0));
        myButton1.setColor(new java.awt.Color(255, 228, 0));
        myButton1.setColorClick(new java.awt.Color(255, 228, 0));
        myButton1.setColorOver(new java.awt.Color(255, 196, 0));
        myButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1403, 817, 130, 70));

        txt_stok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_stok.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        add(txt_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 750, 320, 60));

        txt_hargabeli.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        add(txt_hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 340, 60));

        txt_kodebarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_kodebarang.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        add(txt_kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 620, 310, 60));

        txt_namabarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_namabarang.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        add(txt_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 310, 60));

        txt_keuntungan.setBackground(new java.awt.Color(237, 231, 228));
        txt_keuntungan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_keuntungan.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        txt_keuntungan.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_keuntungan.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_keuntungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keuntunganActionPerformed(evt);
            }
        });
        add(txt_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 750, 340, 60));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 80));

        txt_hargajual.setBackground(new java.awt.Color(237, 231, 228));
        txt_hargajual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_hargajual.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        txt_hargajual.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_hargajual.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_hargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargajualActionPerformed(evt);
            }
        });
        add(txt_hargajual, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 620, 320, 60));

        txtusernamee1.setFont(new java.awt.Font("YouYuan", 1, 18)); // NOI18N
        txtusernamee1.setText("jLabel2");
        add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/dshb (5).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE barang SET keuntungan='"+txt_keuntungan.getText()+"', harga_jual='"+txt_hargajual.getText()
                    +"' WHERE id_barang='"+txt_kodebarang.getText()+"'"; 
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            this.setVisible(false);
            Dashboard.dsh.setVisible(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        clear();
        tampilkanTabel();
        tampilkanTabel1();
        
    }//GEN-LAST:event_myButton1ActionPerformed

    private void txt_keuntunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keuntunganActionPerformed
           // TODO add your handling code here:
           String Harga_Beli = txt_hargabeli.getText();
           String Keuntungan = txt_keuntungan.getText();

        
           int Harga_Jual = Integer.parseInt(Harga_Beli) + Integer.parseInt(Keuntungan);
  
           txt_hargajual.setText("" + Harga_Jual);

    }//GEN-LAST:event_txt_keuntunganActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Dashboard.dsh.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void txt_hargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargajualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargajualActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Button.MyButton myButton1;
    public static final javax.swing.JLabel txt_hargabeli = new javax.swing.JLabel();
    public static javax.swing.JTextField txt_hargajual;
    public static javax.swing.JTextField txt_keuntungan;
    public static final javax.swing.JLabel txt_kodebarang = new javax.swing.JLabel();
    public static final javax.swing.JLabel txt_namabarang = new javax.swing.JLabel();
    public static final javax.swing.JLabel txt_stok = new javax.swing.JLabel();
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables

    
}
