/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import Admin.Dashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.Session;
import static panel.dashboard.tabelbarang;

/**
 *
 * @author asus
 */
public class brg_tmbh extends javax.swing.JPanel {

    /**
     * Creates new form brg_tmbh
     */
    public void tampilkanTabel(){
        DefaultTableModel model = new DefaultTableModel();
        
        tabelbarang.setModel(model);
        
        model.addColumn("kode barang");
        model.addColumn("Nama barang");
        model.addColumn("Harga beli");
        model.addColumn("Keuntungan");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
       try {
            Statement s = koneksi.koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * from barang");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("keuntungan"),
                    rs.getString("harga_jual"),
                    rs.getString("stok"),
                });
                tabelbarang.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
}
}
    private void autocode(){
        try{
            Connection c=koneksi.koneksi.configDB();
            Statement s=c.createStatement();
            String sql="select * from barang order by id_barang desc";
            ResultSet r=s.executeQuery(sql);
            if (r.next()){
                String kodebarang=r.getString("id_barang").substring(2);
                String KB =""+(Integer.parseInt(kodebarang)+1);
                String Nol="";
                if (KB.length()==1){
                    Nol="00"; 
                }else if (KB.length()==2){
                   Nol="0";
                }else if (KB.length()==3){
                    Nol="";}
                    txt_kodebarang.setText("KB" +Nol +KB);
            }else {
                txt_kodebarang.setText("KB001");
            }
            c.close();
            s.close();
        }catch (Exception e){
            System.out.println("autonumber error");
}
    }
    public brg_tmbh() {
        
        initComponents();
        txtusernamee1.setText(Session.get_username());
        autocode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_kodebarang = new javax.swing.JLabel();
        myButton3 = new Button.MyButton();
        txt_namabarang = new javax.swing.JTextField();
        txtusernamee1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1571, 965));
        setPreferredSize(new java.awt.Dimension(1571, 965));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 80));

        txt_kodebarang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_kodebarang.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        add(txt_kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 720, 390, 60));

        myButton3.setBackground(new java.awt.Color(0, 215, 255));
        myButton3.setText("Tambah");
        myButton3.setBorderColor(new java.awt.Color(0, 215, 255));
        myButton3.setColor(new java.awt.Color(0, 215, 255));
        myButton3.setColorClick(new java.awt.Color(0, 201, 235));
        myButton3.setColorOver(new java.awt.Color(0, 158, 195));
        myButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 850, 140, 70));

        txt_namabarang.setBackground(new java.awt.Color(237, 231, 228));
        txt_namabarang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_namabarang.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        txt_namabarang.setMinimumSize(new java.awt.Dimension(4, 33));
        txt_namabarang.setPreferredSize(new java.awt.Dimension(4, 33));
        txt_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namabarangActionPerformed(evt);
            }
        });
        add(txt_namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 720, 460, 60));

        txtusernamee1.setFont(new java.awt.Font("YouYuan", 1, 18)); // NOI18N
        txtusernamee1.setText("jLabel2");
        add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/dshb (7).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1571, 965));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Dashboard.pmsk.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namabarangActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO barang(id_barang, nama_barang) VALUES ('"+txt_kodebarang.getText()+"','"+txt_namabarang.getText()+"')";//id_supplier, nama_supplier, no_hp, alamat) VALUES" + "('"+ is +"','"+ ns +"','"+ nh +"','"+ alamat +"',)";
        java.sql.Connection conn = (Connection)koneksi.koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        this.setVisible(false);
        Dashboard.pmsk.setVisible(true);
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR \n" +e.getMessage());
        }
        tampilkanTabel();
    }//GEN-LAST:event_myButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private Button.MyButton myButton3;
    private javax.swing.JLabel txt_kodebarang;
    public static javax.swing.JTextField txt_namabarang;
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables
}
