/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.koneksi;
import static panel.Pemasokan.txtnamabarang;
import static panel.Pemasokan.txtidbarang;

/**
 *
 * @author asus
 */
public class data_barang extends javax.swing.JFrame {
      public void tampilkanTabel(){
        DefaultTableModel model = new DefaultTableModel();
        
        JTable2.setModel(model);
        
        model.addColumn("Kode Barang");
        model.addColumn("Nama barang");
        model.addColumn("Harga beli");
        model.addColumn("Keuntungan");
        model.addColumn("Harga Jual");
        model.addColumn("Stok");
        
       try {
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT * from barang");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("keuntungan"),
                    rs.getString("harga_jual"),
                    rs.getString("stok"),
                });
                JTable2.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }
    }
      

    /**
     * Creates new form data_barang
     */
    public data_barang() {
         try{
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
            {
                if ("".equals(info.getName()))
                {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(Exception ex){
            
        }
        initComponents();
        JTable2.getTableHeader().setFont(new Font("Fredoka One", Font.CENTER_BASELINE, 16));
        JTable2.getTableHeader().setOpaque(false);
        JTable2.getTableHeader().setBackground(new Color(241,175,9));
        JTable2.getTableHeader().setForeground(new Color(0, 0, 0));
        JTable2.setRowHeight(25);
        
        tampilkanTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttongradient1 = new Button.buttongradient();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 50));

        buttongradient1.setForeground(new java.awt.Color(51, 51, 51));
        buttongradient1.setText("Ok");
        buttongradient1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttongradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, 70, 40));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 50, 40));

        JTable2 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        JTable2.setBackground(new java.awt.Color(173, 172, 172));
        JTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    JTable2.setFocusable(false);
    JTable2.setGridColor(new java.awt.Color(0, 0, 0));
    JTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
    JTable2.setRowHeight(25);
    JTable2.setSelectionBackground(new java.awt.Color(241, 175, 9));
    JTable2.setShowVerticalLines(false);
    JTable2.getTableHeader().setResizingAllowed(false);
    JTable2.getTableHeader().setReorderingAllowed(false);
    JTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            JTable2MouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            JTable2MouseEntered(evt);
        }
    });
    jScrollPane1.setViewportView(JTable2);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 650, 510));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/brgbr (4).png"))); // NOI18N
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void buttongradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient1ActionPerformed
        // TODO add your handling code here:
        int i = JTable2.getSelectedRow();
        TableModel model = JTable2.getModel();
        String nama = model.getValueAt(i, 1).toString();
         String kode = model.getValueAt(i, 0).toString();

        txtidbarang.setText(kode);
        txtnamabarang.setText(nama);
        
        this.setVisible(false);
    }//GEN-LAST:event_buttongradient1ActionPerformed

    private void JTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable2MouseClicked
        // TODO add your handling code here:
       
       int i = JTable2.getSelectedRow();
        /*TableModel model = JTable2.getModel();
        String nama = model.getValueAt(i, 1).toString();
        String kode = model.getValueAt(i, 0).toString();

        txtidbarang.setText(kode);
        txtnamabarang.setText(nama);*/
    }//GEN-LAST:event_JTable2MouseClicked

    private void JTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_JTable2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable JTable2;
    private Button.buttongradient buttongradient1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
