/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Session;
import koneksi.koneksi;

/**
 *
 * @author asus
 */
public class Riwayat_Transaksi extends javax.swing.JPanel {

    /**
     * Creates new form Riwayat_Transaksi
     */
    public void tampilkanTabel(){
        DefaultTableModel model = new DefaultTableModel();
        
        jTable4.setModel(model);
        
        model.addColumn("No Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Kasir");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jumlah");
        model.addColumn("Total");
        
        
       try {
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("SELECT transaksi.id_transaksi,transaksi.tanggal, user.nama_lengkap, barang.nama_barang, "
                    + "barang.harga_jual, detail_transaksi.jumlah, "
                    + "detail_transaksi.total_harga "
                + "FROM user JOIN transaksi ON transaksi.nik = user.nik "
                + "JOIN detail_transaksi ON transaksi.id_transaksi = detail_transaksi.id_transaksi "
                + "JOIN barang ON barang.id_barang = detail_transaksi.id_barang order by transaksi.id_transaksi");
            
            while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_transaksi"),
                    rs.getString("tanggal"),
                    rs.getString("nama_lengkap"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_jual"),
                    rs.getString("jumlah"),
                    rs.getString("total_harga"),
                    
                });
                jTable4.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }
    }
    
    public void datariwayat(){
        String getDate = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(getDate);
        String tanggal = String.valueOf(fm.format(jDate4.getDate()));
        
        DefaultTableModel model = new DefaultTableModel();
        
       
        
        model.addColumn("No Transaksi");
        model.addColumn("Tanggal");
        model.addColumn("Kasir");
        model.addColumn("Nama Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Jumlah");
        model.addColumn("Total");
        
        try{
            String sql = ("select transaksi.id_transaksi, transaksi.tanggal, user.nama_lengkap, barang.nama_barang, barang.harga_jual, detail_transaksi.jumlah, "
                    + "detail_transaksi.total_harga from user join transaksi on transaksi.nik = user.nik join detail_transaksi on "
                    + "transaksi.id_transaksi = detail_transaksi.id_transaksi join barang on barang.id_barang = detail_transaksi.id_barang where transaksi.tanggal='"+tanggal+"'");
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            while(rs.next()){
                model.addRow(new Object[] {
                    rs.getString("id_transaksi"),
                    rs.getString("tanggal"),
                    rs.getString("nama_lengkap"),
                    rs.getString("nama_barang"),
                    rs.getString("harga_jual"),
                    rs.getString("jumlah"),
                    rs.getString("total_harga"),
                    
                });   
            }
            jTable4.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    public Riwayat_Transaksi() {
        initComponents();
         txtusernamee1.setText(Session.get_username());
         tampilkanTabel();
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtusernamee1 = new javax.swing.JLabel();
        jDate4 = new com.toedter.calendar.JDateChooser();
        buttongradient1 = new Button.buttongradient();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        txtpendapat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1571, 965));
        setPreferredSize(new java.awt.Dimension(1571, 965));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusernamee1.setFont(new java.awt.Font("YouYuan", 1, 18)); // NOI18N
        txtusernamee1.setText("jLabel2");
        add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, 150, 30));
        add(jDate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 360, 60));

        buttongradient1.setText("buttongradient1");
        buttongradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient1ActionPerformed(evt);
            }
        });
        add(buttongradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 60, 60));

        jTable4 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable4.getTableHeader().setResizingAllowed(false);
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable4);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 1450, 580));
        add(txtpendapat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 870, 350, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/riwayat Transaksi (5).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 965));
    }// </editor-fold>//GEN-END:initComponents

    private void buttongradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient1ActionPerformed
        // TODO add your handling code here:
        datariwayat();
        String getDate = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(getDate);
        String tanggal = String.valueOf(fm.format(jDate4.getDate()));
        try{
            Statement s = koneksi.configDB().createStatement();
            ResultSet rs = s.executeQuery("select sum(grand_total) from transaksi where tanggal = '"+tanggal+"'");
            while(rs.next()){
                txtpendapat.setText(rs.getString("sum(grand_total)"));
            }
        }catch(Exception e){
            System.out.println("gagal"+e.getMessage());
        }
    }//GEN-LAST:event_buttongradient1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button.buttongradient buttongradient1;
    private com.toedter.calendar.JDateChooser jDate4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable4;
    private javax.swing.JLabel txtpendapat;
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables
}
