/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import Admin.Dashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import koneksi.Session;
import koneksi.koneksi;

/**
 *
 * @author asus
 */
public class Supplier extends javax.swing.JPanel {
     private void autocode(){
        try{
            Connection c=koneksi.configDB();
            Statement s=c.createStatement();
            String sql="select * from Supplier order by id_supplier desc";
            ResultSet r=s.executeQuery(sql);
            if (r.next()){
                String idsupplier=r.getString("id_supplier").substring(2);
                String IS =""+(Integer.parseInt(idsupplier)+1);
                String Nol="";
                if (IS.length()==1){
                    Nol="00"; 
                }else if (IS.length()==2){
                   Nol="0";
                }else if (IS.length()==3){
                    Nol="";}
                    txtid.setText("SP" +Nol +IS);
            }else {
                txtid.setText("SP001");
            }
            c.close();
            s.close();
        }catch (Exception e){
            System.out.println("autocode error");
}
    }
    
    public void ShowData(){
        DefaultTableModel model = new DefaultTableModel();
        
        jTable1.setModel(model);
        model.addColumn("id Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("No HP");
        model.addColumn("Alamat");
        
        try{
        Statement s = koneksi.configDB().createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM supplier");
        
        while(rs.next())
            {
                model.addRow(new Object[] {
                    rs.getString("id_supplier"),
                    rs.getString("nama_supplier"),
                    rs.getString("no_hp"),
                    rs.getString("alamat"),
                    
                });
                jTable1.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }      
    }
    
    public void clear(){
        txtid.setText("");
        txtnamasupplier.setText("");
        txtnohp.setText("");
        txtalamat.setText("");
    }

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        try{
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex){
            ex.getMessage();
             
        }
        initComponents();
        txtnamasupplier.requestFocus();
        autocode();
        ShowData();
         txtusernamee1.setText(Session.get_username());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton1 = new Button.MyButton();
        myButton2 = new Button.MyButton();
        myButton3 = new Button.MyButton();
        txtid = new javax.swing.JLabel();
        txtnamasupplier = new javax.swing.JTextField();
        txtnohp = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtusernamee1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1571, 965));
        setPreferredSize(new java.awt.Dimension(1571, 965));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton1.setBackground(new java.awt.Color(255, 30, 30));
        myButton1.setText("Hapus");
        myButton1.setBorderColor(new java.awt.Color(255, 30, 30));
        myButton1.setColor(new java.awt.Color(255, 30, 30));
        myButton1.setColorClick(new java.awt.Color(255, 10, 11));
        myButton1.setColorOver(new java.awt.Color(255, 33, 0));
        myButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 320, 85, 50));

        myButton2.setBackground(new java.awt.Color(0, 215, 255));
        myButton2.setText("Tambah");
        myButton2.setBorderColor(new java.awt.Color(0, 215, 255));
        myButton2.setColor(new java.awt.Color(0, 215, 255));
        myButton2.setColorClick(new java.awt.Color(0, 201, 235));
        myButton2.setColorOver(new java.awt.Color(0, 158, 195));
        myButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 85, 50));

        myButton3.setBackground(new java.awt.Color(255, 228, 0));
        myButton3.setText("Edit");
        myButton3.setBorderColor(new java.awt.Color(255, 228, 0));
        myButton3.setColor(new java.awt.Color(255, 228, 0));
        myButton3.setColorClick(new java.awt.Color(255, 228, 0));
        myButton3.setColorOver(new java.awt.Color(255, 196, 0));
        myButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 85, 50));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtid.setEnabled(false);
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 310, 60));

        txtnamasupplier.setBackground(new java.awt.Color(237, 231, 228));
        txtnamasupplier.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnamasupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtnamasupplier.setMinimumSize(new java.awt.Dimension(4, 33));
        txtnamasupplier.setPreferredSize(new java.awt.Dimension(4, 33));
        add(txtnamasupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 310, 60));

        txtnohp.setBackground(new java.awt.Color(237, 231, 228));
        txtnohp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtnohp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtnohp.setMinimumSize(new java.awt.Dimension(4, 33));
        txtnohp.setPreferredSize(new java.awt.Dimension(4, 33));
        add(txtnohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 120, 310, 60));

        txtalamat.setBackground(new java.awt.Color(237, 231, 228));
        txtalamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtalamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtalamat.setMinimumSize(new java.awt.Dimension(4, 33));
        txtalamat.setPreferredSize(new java.awt.Dimension(4, 33));
        add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, 310, 60));

        txtusernamee1.setFont(new java.awt.Font("YouYuan", 1, 18)); // NOI18N
        txtusernamee1.setText("jLabel2");
        add(txtusernamee1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 60, 150, 30));

        jTable1.setBackground(new java.awt.Color(173, 172, 172));
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    jTable1.setFocusable(false);
    jTable1.setGridColor(new java.awt.Color(0, 0, 0));
    jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
    jTable1.setRowHeight(25);
    jTable1.setSelectionBackground(new java.awt.Color(241, 175, 9));
    jTable1.getTableHeader().setResizingAllowed(false);
    jTable1.getTableHeader().setReorderingAllowed(false);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTable1MouseEntered(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 1440, 480));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/supplierr (1).png"))); // NOI18N
    add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO supplier VALUES ('"+txtid.getText()+"','"+txtnamasupplier.getText()+"','"+txtnohp.getText()+"','"+txtalamat.getText()+"')";//id_supplier, nama_supplier, no_hp, alamat) VALUES" + "('"+ is +"','"+ ns +"','"+ nh +"','"+ alamat +"',)";
        java.sql.Connection conn = (Connection)koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        this.setVisible(false);
        Dashboard.spl.setVisible(true);
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
        ShowData();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "ERROR \n" +e.getMessage());
        }
        
        
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "UPDATE supplier SET no_hp ='"+txtnohp.getText()+"', alamat='"+txtalamat.getText()
                    +"' where id_supplier ='"+txtid.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            this.setVisible(false);
            Dashboard.spl.setVisible(true);
            JOptionPane.showMessageDialog(null, "Data Berhasil di Edit");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        ShowData();
        clear();
        autocode();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE from supplier WHERE id_supplier='"+txtid.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Hapus Data");
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        ShowData();
        clear();
        autocode();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(i, 0).toString();
        String nama = model.getValueAt(i, 1).toString();
        String nohp = model.getValueAt(i, 2).toString();
        String alamat = model.getValueAt(i, 3).toString();
        

        txtid.setText(id);
        txtnamasupplier.setText(nama);
        txtnohp.setText(nohp);
        txtalamat.setText(alamat);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private Button.MyButton myButton1;
    private Button.MyButton myButton2;
    private Button.MyButton myButton3;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtnamasupplier;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JLabel txtusernamee1;
    // End of variables declaration//GEN-END:variables
}
