/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import koneksi.Session;
import koneksi.koneksi;
import panel.About;
import panel.Barang;
import panel.dashboard;
import panel.Supplier;
import panel.Pemasokan;
import panel.Kasir;
import panel.Riwayat_Transaksi;
import panel.Barang_Masuk;
import panel.Barang_Keluar;
import panel.Brg_edt;
import panel.Pengaturan;
import panel.brg_tmbh;
import static panel.dashboard.be;
import static panel.dashboard.bt;
import static panel.dashboard.btnedit;
import static panel.dashboard.btnhapus;

/**
 *
 * @author asus
 */
public class Dashboard extends javax.swing.JFrame {
     
    
    public static Barang brg; 
    public static dashboard dsh;
    public static Supplier spl;
    public static Pemasokan pmsk;
    public static Kasir ksr;
    public static Riwayat_Transaksi rt;
    public static Barang_Masuk bm;
    public static Barang_Keluar bk;
    public static Pengaturan pg;
    public static brg_tmbh bt;
    public static Brg_edt be;
    public static About ab;
    

    /**
     * Creates new form Dashboard
     * 
     */
    public Dashboard() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        bt = new brg_tmbh();
        be = new Brg_edt();
        brg = new Barang();
        dsh = new dashboard();
        spl = new Supplier();
        pmsk = new Pemasokan();
        ksr = new Kasir();
        rt = new Riwayat_Transaksi();
        bm = new Barang_Masuk();
        bk = new Barang_Keluar();
        pg = new Pengaturan();
        ab = new About();
        
        Panel.add(brg);
        Panel.add(dsh);
        Panel.add(spl);
        Panel.add(pmsk);
        Panel.add(ksr);
        Panel.add(rt);
        Panel.add(bm);
        Panel.add(bk);
        Panel.add(pg);
        Panel.add(bt);
        Panel.add(be);
        Panel.add(ab);
        
        brg.setVisible(true);
        dsh.setVisible(false);
        spl.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        bt.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdatauser = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        buttongradient2 = new Button.buttongradient();
        buttongradient3 = new Button.buttongradient();
        buttongradient4 = new Button.buttongradient();
        buttongradient6 = new Button.buttongradient();
        buttongradient1 = new Button.buttongradient();
        buttongradient7 = new Button.buttongradient();
        buttongradient8 = new Button.buttongradient();
        buttongradient9 = new Button.buttongradient();
        buttongradient10 = new Button.buttongradient();
        buttongradient11 = new Button.buttongradient();
        jLabel22 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 72 (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 40, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 20.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 30, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 71.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 710, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Supplier (9).png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 130, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 53.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 57.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, 40, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 56.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 950, 30, 30));

        txtdatauser.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtdatauser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtdatauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, 200, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Kasir (9).png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 130, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Barang (12)_1.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 52_1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 40, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 51.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 40, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Riwayat Transaksi (2).png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 190, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Barang Keluar (4)_1.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, 170, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Pengaturan (9)_1.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 770, 150, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Logout.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 950, 130, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Pemasokan (1).png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 130, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Barang Masuk (4).png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 69.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 40, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Dashboard (9)_1.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 56 (1)_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 30, 30));

        Panel.setBackground(new java.awt.Color(237, 231, 228));
        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 55, 1590, 960));

        buttongradient2.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttongradient2.setMaximumSize(new java.awt.Dimension(151, 47));
        buttongradient2.setMinimumSize(new java.awt.Dimension(151, 47));
        buttongradient2.setPreferredSize(new java.awt.Dimension(151, 47));
        buttongradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient2ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 300, 50));

        buttongradient3.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        buttongradient3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        buttongradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient3ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 300, 50));

        buttongradient4.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient4ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 300, 50));

        buttongradient6.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient6ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 300, 50));

        buttongradient1.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttongradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 50));

        buttongradient7.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient7ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 300, 50));

        buttongradient8.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient8.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient8ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 300, 50));

        buttongradient9.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient9.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient9ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 940, 300, 50));

        buttongradient10.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient10.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient10ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 300, 50));

        buttongradient11.setForeground(new java.awt.Color(0, 0, 0));
        buttongradient11.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        buttongradient11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttongradient11ActionPerformed(evt);
            }
        });
        getContentPane().add(buttongradient11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 300, 50));

        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, 40, 50));

        jPanel1.setBackground(new java.awt.Color(241, 175, 9));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 10, 100, 40));

        panel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Keuangan (7).png"))); // NOI18N
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttongradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient1ActionPerformed
        // TODO add your handling code here:
        
        brg.setVisible(true);
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        spl.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient1ActionPerformed

    private void buttongradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient2ActionPerformed
        dsh.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        
        brg.setVisible(false);
        spl.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient2ActionPerformed

    private void buttongradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient3ActionPerformed
        // TODO add your handling code here:
        spl.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient3ActionPerformed

    private void buttongradient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient4ActionPerformed
        // TODO add your handling code here:
        pmsk.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        spl.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient4ActionPerformed

    private void buttongradient10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient10ActionPerformed
        // TODO add your handling code here:
        ksr.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        pmsk.setVisible(false);
        spl.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient10ActionPerformed

    private void buttongradient6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient6ActionPerformed
        // TODO add your handling code here:
        rt.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        spl.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false); 
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient6ActionPerformed

    private void buttongradient7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient7ActionPerformed
        // TODO add your handling code here:
        bm.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        spl.setVisible(false);
        bk.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient7ActionPerformed

    private void buttongradient8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient8ActionPerformed
        bk.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        spl.setVisible(false);
        pg.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient8ActionPerformed

    private void buttongradient11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient11ActionPerformed
        // TODO add your handling code here:
        pg.setVisible(true);
        
        btnedit.setVisible(false);
        btnhapus.setVisible(false);
        dsh.setVisible(false);
        brg.setVisible(false);
        pmsk.setVisible(false);
        ksr.setVisible(false);
        rt.setVisible(false);
        bm.setVisible(false);
        bk.setVisible(false);
        spl.setVisible(false);
        be.setVisible(false);
        ab.setVisible(false);
        bt.setVisible(false);
    }//GEN-LAST:event_buttongradient11ActionPerformed

    private void buttongradient9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttongradient9ActionPerformed
       int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakiin Ingin Menutup Aplikasi","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            new LoginB().setVisible(true);

        }
    }//GEN-LAST:event_buttongradient9ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakiin Ingin Menutup Aplikasi","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);

        }
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private Button.buttongradient buttongradient1;
    private Button.buttongradient buttongradient10;
    private Button.buttongradient buttongradient11;
    private Button.buttongradient buttongradient2;
    private Button.buttongradient buttongradient3;
    private Button.buttongradient buttongradient4;
    private Button.buttongradient buttongradient6;
    private Button.buttongradient buttongradient7;
    private Button.buttongradient buttongradient8;
    private Button.buttongradient buttongradient9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel txtdatauser;
    // End of variables declaration//GEN-END:variables
}
