/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author asus
 */
public class Forgot_Password extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_Password
     */
    public Forgot_Password() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtquestion = new javax.swing.JTextField();
        txtanswer = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        myButton1 = new Button.MyButton();
        myButton2 = new Button.MyButton();
        myButton3 = new Button.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1930, 1020));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtquestion.setBackground(new java.awt.Color(237, 231, 228));
        txtquestion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtquestion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquestionActionPerformed(evt);
            }
        });
        getContentPane().add(txtquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 710, 70));

        txtanswer.setBackground(new java.awt.Color(237, 231, 228));
        txtanswer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtanswer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtanswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 710, 70));

        txtpassword.setBackground(new java.awt.Color(237, 231, 228));
        txtpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 710, 70));

        txtusername.setBackground(new java.awt.Color(237, 231, 228));
        txtusername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 710, 70));

        myButton1.setText("Save");
        myButton1.setBorderColor(new java.awt.Color(241, 175, 9));
        myButton1.setColor(new java.awt.Color(241, 175, 9));
        myButton1.setColorClick(new java.awt.Color(241, 175, 9));
        myButton1.setColorOver(new java.awt.Color(241, 160, 7));
        myButton1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 30)); // NOI18N
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 780, 225, 70));

        myButton2.setForeground(new java.awt.Color(241, 175, 9));
        myButton2.setText("Back");
        myButton2.setBorderColor(new java.awt.Color(0, 0, 0));
        myButton2.setColor(new java.awt.Color(0, 20, 17));
        myButton2.setColorClick(new java.awt.Color(0, 20, 17));
        myButton2.setColorOver(new java.awt.Color(0, 0, 0));
        myButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 30)); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 780, 220, 70));

        myButton3.setBackground(new java.awt.Color(153, 153, 153));
        myButton3.setText("Search");
        myButton3.setBorderColor(new java.awt.Color(153, 153, 153));
        myButton3.setColor(new java.awt.Color(153, 153, 153));
        myButton3.setColorClick(new java.awt.Color(153, 153, 153));
        myButton3.setColorOver(new java.awt.Color(102, 102, 102));
        myButton3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 30)); // NOI18N
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 240, 220, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/forgot psswrd (5).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquestionActionPerformed
       
    }//GEN-LAST:event_txtquestionActionPerformed

    private void txtanswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanswerActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
         String username = txtquestion.getText();
        String newPassword = txtpassword.getText();
        String securityQ = txtquestion.getText();
        String answer = txtanswer.getText();

        try{
            //String sql = "select question from user where username ='"+username+"'";
            //java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/rajapakannew","root","13");
            //java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            //java.sql.ResultSet rs = pst.executeQuery(sql);
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/rajapakannew","root","789");
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from user where username ='"+username+"' and answer ='"+answer+"'");

            if(rs.next()){
                st.executeUpdate("update user set password ='"+newPassword+"' where username ='" +username+"' and answer='"+answer+"'");
                JOptionPane.showMessageDialog(null, "Password anda berhasil diperbarui");
                setVisible(false);
                new LoginB().setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Tolong ketik jawaban yang benar");
            conn.close();
            rs.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error in connection");
        }
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginB().setVisible(true);
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        try{

            java.sql.Connection conn = (Connection)koneksi.configDB();
            Statement s = conn.createStatement();
            String sql = ("select question from user where username ='"+txtusername.getText()+"'");
            ResultSet rs = s.executeQuery(sql);

            while(rs.next()){
                txtquestion.setText(rs.getString("question"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_myButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private Button.MyButton myButton1;
    private Button.MyButton myButton2;
    private Button.MyButton myButton3;
    private javax.swing.JTextField txtanswer;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtquestion;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
