package Admin;




import Karyawan.Beranda_Karyawan;
import static Karyawan.KasirK.txt_namaKasir;
import static Karyawan.KasirK.txtnik;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.awt.event.KeyEvent;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Login_RFID extends javax.swing.JFrame {

    /**
     * Creates new form Login_RFID
     */
    public Login_RFID() {
        initComponents();
        txtRFID.requestFocus();
        
        
        
    }

    private void autologin(){
          
        try{
            String sql = "SELECT * FROM user WHERE nik = '"+txtRFID.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);

            if(rs.next()){
                txt_namaKasir.setText(rs.getString(2));
                txtnik.setText(rs.getString(1));
                txtRFID.setText(rs.getString(1));
                if(rs.getString("jabatan").equals("admin")){
                    //Session.set_username(rs.getString("nik"));
                    dispose();
                    new Dashboard().setVisible(true);
                }else if (rs.getString("jabatan").equals("karyawan")){
                    //Session.set_username(rs.getString("nik"));
                    new Beranda_Karyawan().setVisible(true);
                    dispose();
                }

            }else{
                ImageIcon icon = new ImageIcon("image 37.png");
                JOptionPane.showMessageDialog(null,"<html><b style=\"color: black; font-size : 30px\">Password atau Username<br>Yang Anda Masukkan Salah</b><html>","Show",JOptionPane.INFORMATION_MESSAGE,icon);
            }
        }catch (SQLException ex){
            Logger.getLogger(LoginB.class.getName()).log(Level.SEVERE,null, ex);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRFID = new javax.swing.JTextField();
        myButton1 = new Button.MyButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 40 (2).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 650, 60, 50));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 720, 90, 30));

        txtRFID.setBackground(new java.awt.Color(237, 231, 228));
        txtRFID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtRFID.setMinimumSize(new java.awt.Dimension(4, 33));
        txtRFID.setPreferredSize(new java.awt.Dimension(4, 33));
        txtRFID.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtRFIDInputMethodTextChanged(evt);
            }
        });
        txtRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFIDActionPerformed(evt);
            }
        });
        txtRFID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRFIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRFIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtRFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 520, 600, 70));

        myButton1.setForeground(new java.awt.Color(241, 175, 9));
        myButton1.setText("LOGIN");
        myButton1.setBorderColor(new java.awt.Color(51, 51, 51));
        myButton1.setColor(new java.awt.Color(28, 24, 18));
        myButton1.setColorClick(new java.awt.Color(153, 153, 153));
        myButton1.setColorOver(new java.awt.Color(204, 204, 204));
        myButton1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, 600, 70));

        jPanel1.setBackground(new java.awt.Color(241, 175, 9));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 10, 100, 30));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, 40, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Tampilan Awal (15).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         setVisible(false);
         new LoginB().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFIDActionPerformed
    
    }//GEN-LAST:event_txtRFIDActionPerformed

    private void txtRFIDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtRFIDInputMethodTextChanged
   
    }//GEN-LAST:event_txtRFIDInputMethodTextChanged

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
         try{
            String sql = "SELECT * FROM user WHERE nik = '"+txtRFID.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);

            if(rs.next()){
                txt_namaKasir.setText(rs.getString(2));
                txtnik.setText(rs.getString(1));
                txtRFID.setText(rs.getString(1));
                if(rs.getString("jabatan").equals("admin")){
                    //Session.set_username(rs.getString("nik"));
                    dispose();
                    new Dashboard().setVisible(true);
                }else if (rs.getString("jabatan").equals("karyawan")){
                    //Session.set_username(rs.getString("nik"));
                    new Beranda_Karyawan().setVisible(true);
                    dispose();
                }

            }else{
                ImageIcon icon = new ImageIcon("image 37.png");
                JOptionPane.showMessageDialog(null,"<html><b style=\"color: black; font-size : 30px\">Password atau Username<br>Yang Anda Masukkan Salah</b><html>","Show",JOptionPane.INFORMATION_MESSAGE,icon);
            }
        }catch (SQLException ex){
            Logger.getLogger(LoginB.class.getName()).log(Level.SEVERE,null, ex);
        }
            
    }//GEN-LAST:event_myButton1ActionPerformed

    private void txtRFIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){ 
            autologin();
        }
        
    }//GEN-LAST:event_txtRFIDKeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakiin Ingin Menutup Aplikasi","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);

        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txtRFIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFIDKeyReleased
//        // TODO add your handling code here:
//         try{
//            String sql = "SELECT * FROM user WHERE nik = '"+txtRFID.getText()+"'";
//            java.sql.Connection conn = (Connection)koneksi.configDB();
//            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
//            java.sql.ResultSet rs = pst.executeQuery(sql);
//
//            if(rs.next()){
//                txt_namaKasir.setText(rs.getString(2));
//                txtnik.setText(rs.getString(1));
//                txtRFID.setText(rs.getString(1));
//                if(rs.getString("jabatan").equals("admin")){
//                    //Session.set_username(rs.getString("nik"));
//                    dispose();
//                    new Dashboard().setVisible(true);
//                }else if (rs.getString("jabatan").equals("karyawan")){
//                    //Session.set_username(rs.getString("nik"));
//                    new Beranda_Karyawan().setVisible(true);
//                    dispose();
//                }
//
//            }else{
//                ImageIcon icon = new ImageIcon("image 37.png");
//                JOptionPane.showMessageDialog(null,"<html><b style=\"color: black; font-size : 30px\">Password atau Username<br>Yang Anda Masukkan Salah</b><html>","Show",JOptionPane.INFORMATION_MESSAGE,icon);
//            }
//        }catch (SQLException ex){
//            Logger.getLogger(LoginB.class.getName()).log(Level.SEVERE,null, ex);
//        }
    }//GEN-LAST:event_txtRFIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_RFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_RFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_RFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_RFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Login_RFID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private Button.MyButton myButton1;
    private javax.swing.JTextField txtRFID;
    // End of variables declaration//GEN-END:variables
}
