/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;
import static Karyawan.KasirK.txt_namaKasir;
import static Karyawan.KasirK.txtnik;
import Karyawan.Beranda_Karyawan;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.Session;
import koneksi.koneksi;
import static panel.Kasir.txt_namaKasirA;
import static panel.Kasir.txtnikA;
import static panel.Pemasokan.txtnamapetugas;
import static panel.Pemasokan.txtkodepetugas;

/**
 *
 * @author asus
 */
public class LoginB extends javax.swing.JFrame {
    int attempt = 1;

    /**
     * Creates new form LoginB
     */
    public LoginB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        myButton1 = new Button.MyButton();
        jLabel4 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/image 40 (2).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 678, 60, 50));

        myButton1.setForeground(new java.awt.Color(241, 175, 9));
        myButton1.setText("LOGIN");
        myButton1.setBorderColor(new java.awt.Color(51, 51, 51));
        myButton1.setColor(new java.awt.Color(28, 24, 18));
        myButton1.setColorClick(new java.awt.Color(153, 153, 153));
        myButton1.setColorOver(new java.awt.Color(204, 204, 204));
        myButton1.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 24)); // NOI18N
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 668, 600, 70));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 750, 110, 30));

        txtpassword.setBackground(new java.awt.Color(237, 231, 228));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 570, 600, 70));

        jCheckBox1.setBackground(new java.awt.Color(237, 231, 228));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 640, -1, 20));

        txtusername.setBackground(new java.awt.Color(237, 231, 228));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtusername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 450, 600, 70));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, 40, 50));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1850, 0, 40, 50));

        jPanel1.setBackground(new java.awt.Color(241, 175, 9));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 10, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/Tampilan Awal (17)_1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            txtpassword.setEchoChar((char)0);
        }
        else
        txtpassword.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        setVisible(false);
        new Forgot_Password().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        // TODO add your handling code here:
    String sql = "SELECT * FROM user WHERE username = '"+txtusername.getText()+"'AND password='"+txtpassword.getText()+"'";
    //validasiinput();
    if(attempt <= 6){
        try{
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                
                txtusername.setText(rs.getString(4));
                txtpassword.setText(rs.getString(5));
                
                txt_namaKasirA.setText(rs.getString(2));
                txtnikA.setText(rs.getString(1));
                
                txt_namaKasir.setText(rs.getString(2));
                txtnik.setText(rs.getString(1));
                
                txtnamapetugas.setText(rs.getString(2));
                txtkodepetugas.setText(rs.getString(1));
                
                if(rs.getString("jabatan").equals("admin")){
                    Session.set_username(rs.getString("nama_lengkap"));
                    
                    dispose();
                    new Dashboard().setVisible(true);
                }else if (rs.getString("jabatan").equals("karyawan")){
                    Session.set_username(rs.getString("nama_lengkap"));
                    dispose();
                    new Beranda_Karyawan().setVisible(true);
                }
                
            }else {
                validasiinput();
            }
        }catch (SQLException ex){
            Logger.getLogger(LoginB.class.getName()).log(Level.SEVERE,null, ex);
        }
    }else if(attempt != 7){
       //JOptionPane.showMessageDialog(this, "Kesempatan terakhir anda maka anda akan dialihkan ke frame forgot_password");
    }if(attempt == 7){
        dispose();
        new Forgot_Password().setVisible(true);    
    }
    attempt++;
    }//GEN-LAST:event_myButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakiin Ingin Menutup Aplikasi","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);

        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakiin Ingin Menutup Aplikasi","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
            
        }  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
         txtpassword.requestFocus();
    }//GEN-LAST:event_txtusernameActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakiin Ingin Menutup Aplikasi","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private Button.MyButton myButton1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
private boolean validasiinput(){
    boolean valid = false;
    if(txtpassword.getText().trim().isEmpty() && txtusername.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Input username & password"+ attempt);
    }else if(txtusername.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Username tidak boleh kosong" + attempt);
    }else if(txtpassword.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Pasword tidak boleh kosong" + attempt);
    }else{
        JOptionPane.showMessageDialog(null, "Password atau username yang anda input salah" +attempt);
    }   
    return valid;
        
}

}
