/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class Splashscreen extends javax.swing.JFrame {

    /**
     * Creates new form Splashscreen
     */
    public Splashscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingbar = new javax.swing.JProgressBar();
        LoadingValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1930, 1020));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1930, 1020));
        setSize(new java.awt.Dimension(1930, 1020));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(loadingbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 790, 1960, 10));

        LoadingValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0%");
        getContentPane().add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 760, 390, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/kasir (13)_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1930, 1020));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splashscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      Splashscreen sp = new Splashscreen();
      sp.setVisible(true);
      
      try{
          
          for(int i=0; i<=100; i++){
              Thread.sleep(100);
              sp.LoadingValue.setText(i +"%");
              
              if(i == 10){
                  sp.LoadingValue.setText("Turning On Modules...");
              }
              if(i == 20){
                  sp.LoadingValue.setText("Loading Modules...");  
              }
               if(i == 50){
                  sp.LoadingValue.setText("Connecting to Database...");
              }
               if(i == 70){
                  sp.LoadingValue.setText("Connecting to Succesful!");
              }
               if(i == 80){
                  sp.LoadingValue.setText("Launching Application...");
               }
               sp.loadingbar.setValue(i);
          }
          sp.setVisible(false);
          new Login_RFID().setVisible(true);
         
          }catch(Exception e){
              JOptionPane.showMessageDialog(null, e);
      }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar loadingbar;
    // End of variables declaration//GEN-END:variables
}
